imports:
    - { resource: parameters.dist.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    secret: %secret%
    router: { resource: %kernel.root_dir%/config/routing.yml }
    templating: { engines: [twig] }
    form: ~
    validation: { enable_annotations: true }
    session: ~

doctrine:
    dbal:
        driver: %database_driver%
        host: %database_host%
        dbname: %database_name%
        user: %database_user%
        password: %database_password%
    orm:
        auto_mapping: true

hwi_oauth:
    firewall_name: secured_area
    resource_owners:
        github:
            type: github
            client_id: %github_client_id%
            client_secret: %github_client_secret%
            scope: repo
