security:
    providers:
        main:
            entity: { class: Symfio\WebsiteBundle\Entity\User, property: username }

    firewalls:
        api_area:
            pattern: ^/api
            anonymous: ~
            http_basic:
                realm: "Symfio API"

        secured_area:
            pattern: ^
            anonymous: ~
            oauth:
                resource_owners:
                    github: "/login/check-github"
                login_path: /login
                failure_path: /login
                oauth_user_provider:
                    service: symfio.website.user.provider
            logout: ~

    encoders:
        Symfio\WebsiteBundle\Entity\User: plaintext
